<a href="https://colab.research.google.com/github/hasdasda/Generative-AI-for-Developers-Comprehensive-Course/blob/main/Bi%E1%BB%83u_di%E1%BB%85n_t%E1%BB%AB_ng%E1%BB%AF_trong_v%C4%83n_b%E1%BA%A3n_d%C6%B0%E1%BB%9Bi_d%E1%BA%A1ng_vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Some common terms to remember:

1. Corpus
2. Vocabulary
3. Documen
4. Word

### Bag of words

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                   "dswithbappy watch dswithbappy",
                   "people write comment",
                   "dswithbappy write comment"],"output":[1,1,0,0]})

In [3]:
df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(df["text"])

In [6]:
#vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}


In [7]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [8]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 1 0]]
[[0 2 0 1 0]]
[[1 0 1 0 1]]


In [9]:
# new
cv.transform(['Bappy watch dswithbappy']).toarray()

array([[0, 1, 0, 1, 0]])

In [10]:
X = bow.toarray()
y = df['output']

In [11]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 1 0]]
[[0 2 0 1 0]]
[[1 0 1 0 1]]


In [12]:
#Ti gram
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,2))

In [13]:
bow = cv.fit_transform(df["text"])

In [14]:
print(cv.vocabulary_)

{'people': 4, 'watch': 7, 'dswithbappy': 1, 'people watch': 5, 'watch dswithbappy': 8, 'dswithbappy watch': 2, 'write': 9, 'comment': 0, 'people write': 6, 'write comment': 10, 'dswithbappy write': 3}


In [16]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 0 0 1 1 0 1 1 0 0]]
[[0 2 1 0 0 0 0 1 1 0 0]]
[[1 0 0 0 1 0 1 0 0 1 1]]


### TF-IDF (Term Frequency-Inverse document frequency)

In [20]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                   "dswithbappy watch dswithbappy",
                   "people write comment",
                   "dswithbappy write comment"],"output":[1,1,0,0]})
df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [25]:
### Doc để đọc: https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names_out()

array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [26]:
print(X.shape)

(4, 9)


In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid = TfidfVectorizer()

In [27]:
arr = tfid.fit_transform(df['text']).toarray()

In [30]:
arr ### Xem thêm tại https://stackoverflow.com/questions/56115030/converting-tfidfvectorizers-fit-transform-variable-to-an-array-toarray-mak

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [31]:
print(tfid.idf_) ### https://www.datacamp.com/tutorial/role-underscore-python đọc để hiểu tại sao có _

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]
